tech_investement/investor/urls.py
#urlpatterns

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #users
    path('', views.landing_page, name='landing_page'),
    path('deposit/', views.transactions_id, name='transactions_id'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('users/', views.users, name='users'),
    path('recommended_users/', views.recommended_users, name='recommended_users'),
    path('all_users/', views.all_users, name='all_users'),
    path('delete/<int:id>', views.destroy, name='destroy'),
    path('delete_transaction/<int:id>', views.destroy_transaction, name='destroy_transaction'),
    path('destroy_deposit/<int:id>', views.destroy_deposit, name='destroy_deposit'),

    #authentications
    path('auth/login', views.login_view, name='login'),
    path('auth/reset_password/', auth_views.PasswordResetView.as_view(template_name='auth/reset_password.html'), name='reset_password'),
    path('auth/register/', views.register, name='register'),
    path('auth/register/<str:ref_code>/', views.register, name='register'),
    path('auth/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('auth/reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='reset_complete'),
    path('auth/reset_done/', auth_views.PasswordResetDoneView.as_view(), name='reset_done'),
    path('auth/logout/', views.logout_view, name='logout'),
    
    # ******************************************
    # ***************transactions***************
    # ******************************************

    path('transactions/id', views.transactions_id, name='transactions_id'),
    path('transactions_history/', views.transactions_history, name='transactions_history'),
    path('transactions_completed/', views.transactions_completed, name='transactions_completed'),
    path('staff/admin/auth/workplace', views.admin_workplace, name='workplace'),
    path('staff/admin/auth/amount', views.deposit, name='deposit'),
    path('withdraw/', views.withdraw_request, name='withdraw'),
    path('withdraw_status/', views.withdraw_status, name='withdraw_status'),
    path('make_deposit/<int:id>', views.make_deposit, name='make_deposit'),
    path('deposited_amount/', views.deposited_amount, name='deposited_amount'),
    path('make_withdraw/<int:id>', views.make_withdraw, name='make_withdraw'),
    path('destroy_withdraw/<int:id>', views.destroy_withdraw, name='destroy_withdraw'),
    path('amount_withdrawn/', views.amount_withdrawn, name='amount_withdrawn'),

    # Ajax
    path('withdraw_status/completed/', views.withdraw_status_completed, name='withdraw_status_completed'),
    path('withdraw_status/pending/', views.withdraw_status_pending, name='withdraw_status_pending'),
    path('transactions_history/withdraw_completed/', views.withdraw_completed, name='withdraw_completed'),
    path('transactions_history/deposit_completed/', views.deposit_completed, name='deposit_completed'),
    # ############################################
    # ################transactions################
    # ############################################


    #assets
    path('assets/', views.assets, name='assets'),
    path('purchase/<int:id>', views.purchase_item, name='purchase_item'),
    path('purchase/success/<int:id>/', views.purchase_success, name='purchase_success'),
    path('purchased_items/', views.purchased_items, name='purchased_items'),

    #admin
    
    path('staff/admin/auth/admin_login/', views.adminLogin, name='admin_login'),
    path('staff/admin/auth/adminDashboard', views.adminDashboard, name='adminDashboard'),
    path('staff/admin/auth/admin_workplace/', views.admin_workplace, name='admin_workplace'),
    path('staff/admin/auth/admin_logout/', views.admin_logout, name='admin_logout'),
    path('staff/admin/auth/admin_users/', views.admin_users, name='admin_users'),

    #charts(ajax)
    path('get_chart_data/', views.get_chart_data, name='get_chart_data'),
    path('get_transaction/', views.get_transaction, name='get_transaction'),
    
    # refresh customers
    path('customers/', views.customers, name='customers'),

    # refresh deposited
    path('deposited/', views.deposited, name='deposited'),

    # refresh withdrawn
    # path('withdrawn/', views.withdrawn, name='withdrawn'),
    
    # refresh_balance
    path('refresh_balance/', views.refresh_balance, name='refresh_balance'),
   ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tech_investement/tech_investement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", include("investor.urls")),
]

tech_investement/investor/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User, AbstractUser
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from .utils import generate_uuid

# Create your models here.
class UserProfile(AbstractUser):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    username = models.CharField(max_length=12, unique=True, null=False, blank=False, default=True)
    registration_number = models.CharField(max_length=50, blank=True)
    email = models.EmailField(unique=True, null=False, blank=False)
    phone_number = models.BigIntegerField()
    date_joined = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=50, blank=True)
    recommended_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="recommended",
        verbose_name="recommended by",
        help_text="The user who recommended this user.",
    )

    groups = models.ManyToManyField(
        "auth.Group",
        blank=True,
        related_name="user_profiles",
        verbose_name="groups",
        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
    )
    user_permissions = models.ManyToManyField(
        "auth.Permission",
        blank=True,
        related_name="user_profiles",
        verbose_name="user permissions",
        help_text="Specific permissions for this user.",
    )

    def __str__(self):
        return f"{self.username} - {self.code}"

    def save(self, *args, **kwargs):
        # Check if the user already has a code
        if self.code == "" or self.registration_number == "":
            # Generate a new code for the user
            code = generate_uuid()
            registration_number = generate_uuid()
            self.code = code
            self.registration_number = registration_number
        super().save(*args, **kwargs)

        # Check if the user already has a UserAccount instance
        if not hasattr(self, 'UserAccount'):
            # Create a new Wallet instance for the user
            UserAccount.objects.create(user=self, username=self.username, amount_paid=0, balance=0)
        
        # list of recommended profiles
        def get_recommended_profiles(self):
            qs = UserProfile.objects.all()
            my_recommended_profiles = []
            for profile in qs:
                if profile.recommended_by == self.user:
                    my_recommended_profiles.append(profile)
            return my_recommended_profiles


class UserAccount(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE, related_name='UserAccount') 
    username = models.CharField(max_length=12, unique=True, null=False, blank=False, default=True)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    bonus = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    transactions_id = models.CharField(max_length=12)
    date = models.DateTimeField(auto_now_add=True)
    bonus_given = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.user.username} - Amount Paid: {self.amount_paid}, Balance: {self.balance}"

# # transactions
class Transaction_ids(models.Model):
    user = models.CharField(max_length=50)
    transactions_id = models.CharField(max_length=12)
    name = models.CharField(max_length=12, null=False, blank=False)
    amount_deposited = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f" {self.user}, Transactions ID: {self.transactions_id}, Date: {self.date}"

# # deposits
class Deposit(models.Model):
    username = models.CharField(max_length=12, null=False, blank=False)
    name = models.CharField(max_length=12, null=False, blank=False)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2)
    phone_number = models.IntegerField(null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    transactions_id = models.CharField(max_length=12, null=False, blank=False)
    def __str__(self):
        return f"{self.username} - Amount: {self.amount_paid}, Date: {self.date}"

#  withdrawals
class Withdrawal(models.Model):
    username = models.CharField(max_length=12, null=False, blank=False)
    phone_number = models.IntegerField(null=False, blank=False)
    name = models.CharField(max_length=12, null=False, blank=False)
    withdrawn = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.username} - Amount: {self.withdrawn}, Date: {self.date}"

# amount withrawn
class WithdrawalRequest(models.Model):
    username = models.CharField(max_length=12, null=False, blank=False)
    phone_number = models.IntegerField(null=False, blank=False)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    confirmation_name = models.CharField(max_length=12, null=False, blank=False)
    status = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.username} - Amount: {self.amount}, Date: {self.date}"


class Item(models.Model):
    name = models.CharField(max_length=12, null=False, blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    title = models.CharField(max_length=12, null=False, blank=False)
    description = models.TextField()
    image = models.ImageField(upload_to='assets/', null=True, blank=True)
    release_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    release_date = models.DateTimeField(auto_now_add=True)

    def update_user_balance(self):
        from datetime import timedelta
        users = UserAccount.objects.filter(transactions_id=self.id)
        for user in users:
            # Check if the last balance update was more than 1 day ago
            last_update = user.date
            if not last_update or timezone.now() - last_update >= timedelta(minutes=1):
                user.balance += self.release_amount
                user.date = timezone.now()
                user.save()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # Call the update_user_balance method when the item is saved
        self.update_user_balance()

    @property
    def is_released(self):
        return timezone.now() >= self.release_date

    def __str__(self):
        return f"Asset Name: {self.name}, Asset Value: {self.price}, Release Amount: {self.release_amount}, Release Date: {self.release_date}"

class Purchase(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    profit = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    release_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    title = models.CharField(max_length=12, null=False, blank=False, default=True)
    description = models.TextField()
    image = models.FileField(upload_to='assets/', null=True, blank=True)
    purchase_date = models.DateTimeField(default=timezone.now)
    released = models.BooleanField(default=False)

    def release_item(self):
        if self.item.is_released() and not self.released:
            # Perform release operation
            # For example, add released amount to user's balance
            # or grant access to some resource, etc.
            self.user.UserAccount.balance += self.item.release_amount
            self.user.UserAccount.save()
            self.released = True
            self.save()

    def __str__(self):
        return f"{self.user.username} purchased {self.item.name} on {self.purchase_date}"

tech_investement/investor/forms.py
from django import forms

from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile, UserAccount, Deposit, Withdrawal, WithdrawalRequest

#   *****authentication forms****
# registration
class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True, max_length=254)
    username = forms.CharField(required=True, max_length=254)
    password1 = forms.CharField(required=True, max_length=15, widget=forms.PasswordInput())
    password2 = forms.CharField(required=True, max_length=15, widget=forms.PasswordInput())

    class Meta:
        model = User 
        fields = ["username".lower(), "email","password1", "password2"]

# user profile
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['email', 'phone_number','username']

# login
class loginForm(forms.Form):
    username = forms.CharField(max_length=15)
    password = forms.CharField(max_length=15, widget=forms.PasswordInput())
    
    class Meta:
        fields = ["username", "password"]

# reset password
class reset_passwordForm(forms.Form):
    # username = forms.CharField(max_length=12)
    # password = forms.CharField(max_length=12, widget=forms.PasswordInput())
    # confirm_password = forms.CharField(max_length=12, widget=forms.PasswordInput())
    
    # class Meta:
    #     fields = ["username", "password","confirm_password"]
    pass

# transaction
class transactions_id_form(forms.ModelForm):
    class Meta:
        model = UserAccount
        fields = ['transactions_id']

class user_deposit_form(forms.ModelForm):
    class Meta:
        model = Deposit
        fields = ['transactions_id', 'amount_paid','name']

class deposit_form(forms.ModelForm):
    class Meta:
        model = UserAccount
        fields = ['balance']

class withdraw_form(forms.ModelForm):
    class Meta:
        model = WithdrawalRequest
        fields = ['amount', 'phone_number', 'confirmation_name']

# search form
class searchForm(forms.Form):
    search = forms.CharField(max_length=12)

    class Meta:
        fields = ["search"]

class StkpushForm(forms.Form):
    # phone_number must start with 254 and be 12 digits long
    phone_number = forms.CharField(max_length=12)
    amount = forms.IntegerField()
    # account_reference = forms.CharField(max_length=12)
    # transaction_description = forms.CharField(max_length=12)

    class Meta:
        fields = ["phone_number", "amount"]

    pass

# deposit form
class depositForm(forms.Form):
    amount = forms.IntegerField()

    class Meta:
        fields = ["amount"]



# letter form
class letterForm(forms.Form):
    message = forms.CharField(max_length=100)
    color = forms.CharField(max_length=12)
    font = forms.CharField(max_length=12)
    class Meta:
        fields = ["message","color", "font"]

tech_investement/investor/templates/transactions/deposit.html
<!-- //myapp/templates/show.html -->
{% extends "base.html" %}
  
{% block title %}Deposits {% endblock title %}
  
{% block heading %}Deposits {% endblock heading %}

{% block content %}
 <div class="col-md-12">
        <span><a href="/dashboard/" class="btn btn-primary">New Deposit</a></span>  
        <div class="table-responsive">
			<!-- message -->
		{% for message in messages %}
				{% if "success" in message.tags %}
				<span id='message' style="color: green; top: 10%;">{{ message }}</span>
				{% else %}
					<span id='message' style="color: red; top: 10%;">{{ message }}</span>
				{% endif %}
			{% endfor %}

		<table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
        <thead>
            <th><input type="checkbox" id="checkall" /></th>
            <th>ID</th>
            <th>Username</th>
			<th>Transaction Id</th>
			<th>Name</th>
			<th>Amount Deposited</th>
			<th>phone_number</th>
			<th>Date</th>
            <th>Edit</th>
            <th>Deposit</th>
			<th>Delete</th>
        </thead>
        <tbody>
        {% for user in user  %}  
            <tr>  
            <td><input type="checkbox" class="checkthis" /></td>
            <td>{{ user.id }}</td> 
            <td>{{ user.username }}</td>
			<td style="font-size: 1.4rem; font-weight: 900;">{{ user.transactions_id }}</td>
			<td>{{ user.name }}</td>
			<td>{{ user.amount_paid }}</td>
			<td>{{ user.phone_number }}</td>
			<td>{{ user.date }}</td>
            <td><a href="/edit_deposit/{{ user.id }}" class="btn btn-primary">Edit</a></td>
            <td><a href="/make_deposit/{{ user.id }}" class="btn btn-success">Deposit</a></td>  
            <td><a href="/destroy_deposit/{{ user.id }}" class="btn btn-danger">Delete</a></td>
			</tr>  

		{% endfor %}
        </tbody>
        </table>
        </div>
    </div>
{% endblock content %}

tech_investement/investor/templates/transactions/deposit_completed.html
<div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
        <thead>
            <th><input type="checkbox" id="checkall" /></th>
            <th>ID</th>
            <th>username</th>
			<th>Transaction id</th>
			<th>Name</th>
			<th>Amount Deposited</th>
            <th>Edit</th>
            <th>Delete</th>
        </thead>
        <tbody>
        {% for transaction in transactions  %}  
            <tr>  
            <td><input type="checkbox" class="checkthis" /></td>
            <td>{{ transaction.id }}</td> 
            <td>{{ transaction.user }}</td>  
			<td>{{ transaction.transactions_id }}</td>
			<td>{{ transaction.name }}</td>
			<td>{{ transaction.amount_deposited }}</td>
            <td><a href="/edit/{{ user.id }}" class="btn btn-primary">Edit</a></td>
            <td><a href="/delete_transaction/{{ transaction.id }}" class="btn btn-danger">Delete</a></td>  
            </tr>  

		{% endfor %}
        </tbody>
        </table>
        </div>

tech_investement/investor/templates/transactions/edit_deposit.html
<!-- //myapp/templates/edit.html -->
{% extends "base.html" %}
  
{% block title %}Add New Employee Records{% endblock title %}
  
{% block content %}
<div class="col-md-12">
    <form method="POST" class="post-form" action="/edit_deposit/{{user.id}}">  
    {% csrf_token %}  
    <div class="container">   
        <div class="col-12">  
            <h3>Update Details</h3>  
        </div> 
        <div class="mb-3"> 
            <label>Transaction ID:</label>  
            <input type="text" class="form-control" name="name" id="id_name" required maxlength="100" value="{{ employee.name }}" />  
        </div> 
        <div class="mb-3"> 
            <label>Amount:</label>  
            <input type="email" class="form-control" name="email" id="id_email" required maxlength="254" value="{{ employee.email }}" />  
        </div> 
        <div class="mb-3"> 
            <button type="submit" class="btn btn-success btn-lg">Update</button>  
        </div> 
    </div>  
    </form>  
{% endblock content %}   

tech_investement/investor/templates/transactions/transactions_history.html
<!-- //myapp/templates/show.html -->
{% extends "base.html" %}

{% load static %}
  
{% block title %}Transactions History{% endblock title %}

{% block heading %}Transactions History{% endblock heading %}
  
{% block content %}
 <div class="col-md-12">
	 <span><a hx-get="{% url "deposit_completed" %}" hx-target="#history" hx-push-url="false" class="btn btn-primary">Deposited
				<img style="width: 20px;"  class="htmx-indicator" src="{% static "images/ZKZg.gif" %}">
		 </a></span>
        <span><a hx-get="{% url "withdraw_completed" %}" hx-target="#history" hx-push-url="false" class="btn btn-primary">Withdrawals
				<img style="width: 20px;"  class="htmx-indicator" src="{% static "images/ZKZg.gif" %}">
			</a></span>
		<div id="history" ></div>
        
    </div>
{% endblock content %}

tech_investement/investor/templates/transactions/withdraw_completed.html
<div class="col-md-12">
<div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
        <thead>
            <th><input type="checkbox" id="checkall" /></th>
            <th>ID</th>
            <th>username</th>
			<th>Amount Withdrawn</th>
			<th>Confirmation name</th>
			<th>Date</th>
            <th>Edit</th>
            <th>Delete</th>
        </thead>
        <tbody>
        {% for withdraw in withdraw  %}  
            <tr>  
            <td><input type="checkbox" class="checkthis" /></td>
            <td>{{ withdraw.id }}</td> 
            <td>{{ withdraw.username }}</td> 
            <td>{{ withdraw.withdrawn }}</td>
			<td>{{ withdraw.name }}</td>
			<td>{{ withdraw.date }}</td>
            <!-- <td><a href="/edit/{{ user.id }}" class="btn btn-primary">Edit</a></td> -->
            <!-- <td><a href="/delete_transaction/{{ transaction.id }}" class="btn btn-danger">Delete</a></td> -->  
            </tr>  

		{% endfor %}
        </tbody>
        </table>
        </div>

tech_investement/investor/templates/transactions/withdrawal.html
<!-- //myapp/templates/show.html -->
{% extends "base.html" %}
  
{% block title %} Withdraw {% endblock title %}
  
{% block heading %} Withdraw {% endblock heading %}

{% block content %}
 <div class="col-md-12">
        <div class="table-responsive">
			<!-- message -->
		{% for message in messages %}
				{% if "success" in message.tags %}
				<span id='message' style="color: green; top: 10%;">{{ message }}</span>
				{% else %}
					<span id='message' style="color: red; top: 10%;">{{ message }}</span>
				{% endif %}
			{% endfor %}

		<table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
        <thead>
            <th><input type="checkbox" id="checkall" /></th>
            <th>ID</th>
            <th>Username</th>
			<th>phone number</th>
			<th>confirmation name</th>
			<th>Amount Withdrawn</th>
			<th>Date</th>
            <th>Edit</th>
            <th>Action</th>
			<th>Delete</th>
        </thead>
        <tbody>
        {% for user in user  %}  
            <tr>  
            <td><input type="checkbox" class="checkthis" /></td>
            <td>{{ user.id }}</td> 
            <td>{{ user.username }}</td>
			<td>{{ user.phone_number }}</td>
			<td>{{ user.confirmation_name }}</td>
			<td>{{ user.amount }}</td>
			<td>{{ user.date }}</td>
            <td><a href="/edit_withdraw/{{ user.id }}" class="btn btn-primary">Edit</a></td>
            <td><a href="/make_withdraw/{{ user.id }}" class="btn btn-success">Withdraw</a></td>  
            <td><a href="/destroy_withdraw/{{ user.id }}" class="btn btn-danger">Delete</a></td>
			</tr>  
		{% endfor %}
        </tbody>
        </table>
        </div>
    </div>
{% endblock content %}